name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Aggregator Docker image
      working-directory: src/MetricAggregator
      run: docker build . -t tinygator.aggregator:$(date +%s)
    - name: Build the Collector Docker image
      working-directory: src/MetricCollector
      run: docker build . -t tinygator.collector:$(date +%s)
